### ISSUE TITLE
No apt-get package manager for MacOS

### ISSUE THREAD

**Issue by bunnycodec** [RaisinTen/fs-make#11]
**Is your feature request related to a problem? Please describe.**
Yes. My mac machine doesn't have an apt-get package manager. 

**Describe the solution you'd like**
Provide some alternative or detail explanation about what users need to do to successfully use fs-make. Try installing the missing tools using brew or MacPorts automatically for the users.

**Describe alternatives you've considered**
Some recommendations in the cli about the next possible steps they can execute. 
A path to install the required tools.
A readme file or help would be nicer for more info

**Additional context**
A mac system doesn't come default with any package manager installed in it. 
So enlightening Mac users with some possible solutions from your end would be helpful.
Works like magic after all dependencies are installed.

**Comment by RaisinTen** [comment]
Thank you very much for bringing this up. I'll try to solve this ASAP. Cheers! :smile:

**Comment by RaisinTen** [comment]
Hello @bunnycodec! I've made some changes. You may take a look at the test runs linked in the "**How Has This Been Tested?**" section of the [pr](https://github.com/RaisinTen/fs-make/pull/12).

If you want to test it locally:
1. clone the repo:
    ```sh
    $ git clone https://github.com/RaisinTen/fs-make.git
    $ cd fs-make
    ```
2. checkout the [`configuration-improvements`](https://github.com/RaisinTen/fs-make/tree/configuration-improvements) branch:
    ```sh
    $ git checkout configuration-improvements
    ```
and build it.

Do tell me if you're satisfied with the changes. Accordingly, I'll merge the pr.

Cheers! :slightly_smiling_face:
